version: 2.1

workflows:
  build_and_test:
    jobs:
      - build:
          filters:
            branches:
              ignore: development

      - deploy_stable:
          requires:
            - build
          filters:
            branches:
              only: stable

jobs:
  build:
    docker:
      - image: circleci/python:3.8

    steps:
      - checkout
      - setup_remote_docker

      - run:
          name: Build Docker Image
          command: |
            docker build -t parisnk/$IMAGE_NAME:$CIRCLE_SHA1 . -f .docker/Dockerfile

      - deploy:
          name: Deploy docker images to docker hub
          command: |
            echo $DOCKERHUB_PASSWORD | docker login --username $DOCKERHUB_USERNAME --password-stdin
            docker push parisnk/$IMAGE_NAME:$CIRCLE_SHA1

  deploy_stable:
    docker:
      - image: circleci/python:3.8

    steps:
      - checkout
      - setup_remote_docker

      - run:
          name: Pull images down from docker hub
          command: |
            echo $DOCKERHUB_PASSWORD | docker login -u $DOCKERHUB_USERNAME --password-stdin
            docker pull "${DOCKERHUB_USERNAME}/${IMAGE_NAME}:${CIRCLE_SHA1}"

      - run:
          name: update docker images with tag latest
          command: |
            docker tag "${DOCKERHUB_USERNAME}/${IMAGE_NAME}:${CIRCLE_SHA1}" "${DOCKERHUB_USERNAME}/${IMAGE_NAME}:latest"

      - run:
          name: update docker images with tag stable
          command: |
            docker tag "${DOCKERHUB_USERNAME}/${IMAGE_NAME}:${CIRCLE_SHA1}" "${DOCKERHUB_USERNAME}/${IMAGE_NAME}:stable"

      - deploy:
          name: Push docker images to docker hub
          command: |
            docker push parisnk/$IMAGE_NAME:latest
            docker push parisnk/$IMAGE_NAME:stable
