version: '3.7'

services:
  proxy:
    image: parisnk/component-proxy:latest
    ports:
      - 9080:9080
    environment:
      COMPONENT_RECIPES_ENABLED: 0
      COMPONENT_LOGGING_ENABLED: 0
      COMPONENT_AUTH_ENABLED: 0

    networks:
      - component-proxy

networks:
  component-proxy:
    external: true